spring:
  application:
    name: spring-boot-admin-server
  boot:
    admin:
      client:
        url: http://localhost:8080
        instance:
          metadata:
            tags:
              environment: test
---
spring:
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      client:
        username: admin
        password: admin
        instance:
          metadata:
            user.name: admin
            user.password: admin
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
info.tags.security: secured